name: "Pull Request Labeler"

on:
    pull_request_target:
      branches:
        - "master"
        - "prowler-4.0-dev"

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
